


# Если код работает правильно, excepation не будет.

try:
	print(X)
except:
	print('An exception ocurred')


